config/routes.rb
ActionController::Routing::Routes.draw do |map|

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
  map.resources :users
  map.login 'login', :controller => 'user_sessions', :action => 'new'
  map.logout 'logout', :controller => 'user_sessions', :action => 'destroy'
  map.resources :user_sessions
  
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :assignments
	has_many :users, :through => :assignments
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :assignments
	has_many :roles, :through => :assignments
	acts_as_authentic
	def role_symbols
		roles.map do |role|
			role.name.underscore.to_sym
		end
	end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def assignRoles
		@users=Users.find(:all)
		@roles=Roles.find(:all)
	end
end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
  helper_method :current_user
  protected
  def current_user_session
	return @current_user_session if defined?(@current_user_session)
	@current_user_session=UserSession.find
  end
  
  def current_user
	@current_user = current_user_session && current_user_session.record
  end

	before_filter :check_authorization  
	def check_authorization
		Authorization.current_user = self.current_user
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
filter_resource_access
	def index
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
		@user_session = UserSession.new
  end

  def create
		@user_session = UserSession.new(params[:user_session])
		if @user_session.save
			flash[:notice] = "Successfully logged in."
			redirect_to :controller => 'home'
			
		else
			render :action => 'new'
		end
  end

  def destroy
		@user_session=UserSession.find
		@user_session.destroy
		flash[:notice] = "Successfully logged out."
		redirect_to :controller => 'home'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#filter_resource_access
	def index
		@users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])  
		if @user.save  
		 flash[:notice] = "Registration successful."  
		 redirect_to :controller=>'home'
		else  
		#     redirect_to :controller=>'users', :action => 'new'
		 render :action => 'new'
		end
	end

	def monitor
	end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(:action => 'index', :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end #end if
     end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<html>
<head>
	<title>Home</title>
</head>
<body>
	<% if permitted_to? :monitor, :users %>
		<%= link_to 'monitor', :controller => 'users', :action => 'monitor' %>
	<% end %>

	<br/>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumyeirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diamvoluptua.
	<br/>At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
	<br/>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumyeirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diamvoluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumyeirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diamvoluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumyeirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diamvoluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumyeirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diamvoluptua.
	<br/>At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
	
</body>
</html>

app/views/layouts/application.html.erb
<html>
<body>
	<div align="right" id="user_nav">
		<% if current_user%> 
			<%= link_to "Edit profile", :controller => 'users', :action => 'edit', :id => current_user  -%> |
			<%= link_to "Logout", logout_path -%>
		<% else %>
			<%= link_to "Register", new_user_path -%> | 
			<%= link_to "Log in", login_path -%>
		<% end %>
	</div>
	<%= yield -%>
</body>
</html>

app/views/user_sessions/new.html.erb
<head>
	<title>Log in</title>
</head>

 <% form_for @user_session, :url => {:action => 'create'} do |form| %>  
 <%= form.error_messages %>  
     <%= form.label :username, "Username" %>  
     <%= form.text_field :username %>  
     <%= form.label :password, "Password" %>  
     <%= form.password_field :password %>  
     <%= form.submit "Submit" %>  
 <% end %>

app/views/users/_user.html.erb
<% form_for @user, :url => {:action => 'create'} do |form| %>  
<%= form.error_messages %>  
	<%= form.label :username, "Username" -%> <br/>
	<%= form.text_field :username -%>  <br/><br/>
	<%= form.label :email, "Email" -%>  <br/>
	<%= form.text_field :email -%>  <br/><br/>
	<%= form.label :password, "Password" -%>  <br/>
	<%= form.password_field :password -%>  <br/><br/>
	<%= form.label :password_confirmation, "Password confirmation" -%>  <br/>
	<%= form.password_field :password_confirmation -%>  <br/><br/>
	<% for role in Role.find(:all) %>
		<div>  
			<%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>  
			<%= role.name %>  
		</div>  
	<% end %>
	<%= form.submit "Submit" %>  <br/>
<% end %> 

app/views/users/edit.html.erb
<h1>Editing user: <%= h @user.username%></h1>
<% form_for @user, :url => {:action => 'update', :id => @user} do |form| %>  
<%= form.error_messages %>

		<%= form.label :username, "Username" -%> <br/>
		<%= form.text_field :username -%>  <br/><br/>
		<%= form.label :email, "Email" -%>  <br/>
		<%= form.text_field :email -%>  <br/><br/>
		<%= form.label :password, "Password" -%>  <br/>
		<%= form.password_field :password -%>  <br/><br/>
		<%= form.label :password_confirmation, "Password confirmation" -%>  <br/>
		<%= form.password_field :password_confirmation -%>  <br/><br/>
		<% for role in Role.find(:all) %>
			<div>  
				<%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>  
				<%= role.name %>  
			</div>  
		<% end %>  
		<%= form.submit "Submit" %>  <br/>
<% end %> 

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%=h user.username %></td>
    <td><%= link_to 'Show', :action => 'show', :id => user %></td>
    <td><%= link_to 'Edit', :action => 'edit', :id => user %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/monitor.html.erb
	<html>
	<head>
		<title>Monitor</title>
	</head>
	<body>
		<br/>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumyeirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diamvoluptua.
		<br/>At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
		<br/>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumyeirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diamvoluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumyeirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diamvoluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumyeirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diamvoluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumyeirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diamvoluptua.
		<br/>At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
		
	</body>
	</html>	

app/views/users/new.html.erb
<head><title>Register</title></head>
<%= render @user -%>

app/views/users/show.html.erb
<p>
  <b>Name:</b>
  <%=h @user.username %>
</p>


<%= link_to 'Edit', :action => 'edit', :id => @user%> |
<%= link_to 'Back', :action => 'index' %>